---
title: "Gráficas por cruces"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Gráficas por cruces}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# library(encuestar)
library(dplyr)
devtools::load_all()
```
```{r correcciones_data}
datos_demo <- datos_demo |> mutate(across(contains("evaluacion_"), ~as.numeric(.x)))
cuestionario_demo <-  cuestionario_demo|> 
  mutate(tema = if_else(llaves =="evaluacion_amlo", "AMLO", tema),
         tema = if_else(llaves =="evaluacion_rutilio", "Rutilio", tema)
  )
```

```{r clase_grafica}
diseno <- survey::svydesign(ids = ~1, data = datos_demo)

Cr <- Cruce$new(diseno = diseno, diccionario = cuestionario_demo, tema = tema_default)

```
# Cruce por puntos
```{r, fig.width=11, fig.height=11, echo = FALSE}

variablesConocimiento <- cuestionario_demo %>%
  filter(grepl(pattern = "Bloque 3", x = bloque)) |>
  filter(grepl(pattern = "conocimiento_", x = llaves)) |>
  pull(llaves)

Cr$puntos(cruce = "sexo",
          variables = variablesConocimiento,
          vartype = "cv", valor_variables = "Sí")

```
# Cruce brechas duales
```{r, fig.width=11, fig.height=11, echo = FALSE}

Cr$brechasDuales(var1 = "AMAI_factor",
                 var2_filtro = "candidato_preferencia",
                 filtro = c("Carlos Morales", "Sasil de León", "Eduardo Ramírez Aguilar"),
                 vartype = "cv",
                 line_rich = F,
                 line_linewidth = 2, line_hjust = 0.5, line_vjust = -0.5)

```
# Cruce brechas multiples
```{r, fig.width=11, fig.height=11, echo = FALSE}

Cr$brechasMultiples(por_grupo = "AMAI_factor",
                    variables=c("conocimiento_manuelita",
                                "conocimiento_carlos",
                                "conocimiento_era",
                                "conocimiento_sasil"),
                    valor_variables = "Sí", vartype = "cv", line_rich = F,
                    line_linewidth = 2, line_hjust = "ymax", line_vjust = -0.5)

```
# Cruce barras multiples
```{r, fig.width=11, fig.height=11, echo = FALSE}

Cr$barrasMultiples(por_grupo = "AMAI_factor", variables = c("conocimiento_manuelita",
                                                   "conocimiento_carlos",
                                                   "conocimiento_era",
                                                   "conocimiento_sasil"), valor_variables = "Sí", vartype = "cv", color = "red")

```
# Cruce bloques
```{r, fig.width=11, fig.height=11, echo = FALSE}

Cr$bloques(cruce = "seg_voto", filter = c("Ns/Nc", NA),
           variable = "voto_candidato",
           vartype = "cv")

```
