---
title: "Gráficas especiales"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Gráficas especiales}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# library(encuestar)
library(dplyr)
devtools::load_all()
```

```{r correcciones_data}
datos_demo <- datos_demo |> mutate(across(contains("evaluacion_"), ~as.numeric(.x)))
cuestionario_demo <-  cuestionario_demo|> 
  mutate(tema = if_else(llaves =="evaluacion_amlo", "AMLO", tema),
         tema = if_else(llaves =="evaluacion_rutilio", "Rutilio", tema)
  )
```

```{r clase_grafica}
diseno <- survey::svydesign(ids = ~1, data = datos_demo)

Es <- Especial$new(diseno = diseno, diccionario = cuestionario_demo, tema = tema_default)

```

# Candidato opinion

```{r}
Es$candidatoOpinion(patron_inicial = "opinion",
                     aspectos = c("era", "sasil"), ns_nc = "Ns/Nc (No leer)", regular = "Regular (No leer)",
                     grupo_positivo= c("Buena"), grupo_negativo = c("Mala"),
                     orden_resp = c("Mala", "Regular (No leer)", "Buena"))

```
```{r}
Es$candidatoOpinion(patron_inicial = "opinion", llave_burbuja = NA,
                     aspectos = c("era", "sasil"), ns_nc = "Ns/Nc (No leer)", regular = "Regular (No leer)",
                     grupo_positivo= c("Buena"), grupo_negativo = c("Mala"),
                     orden_resp = c("Mala", "Regular (No leer)", "Buena"))

```
# Candidato partido

```{r}
nombres_candidatos <- cuestionario_demo %>%
  filter(grepl(pattern = "Bloque 5:", x = bloque)) |>
  filter(grepl("partido_",llaves)) %>%
  pull(tema)

color_morena <- "#A6032F"
color_morena_complemento <- "#F5CD5F"
color_panal <- "#03A6A6"
color_pt <- "#D91136"
color_pri <- "#038C33"
color_mc <- "#F27405"
color_pvem <- "#98BF5E"
color_pan <- "#0339a6"
color_prd <- "#F2B705"

color_pencsolchis <- "#AE95BF"
color_chisunido <- "#0396A6"
color_rspchis <-"#D9526B"
color_pmchis <- "#6B3A8C"

color_otro <- "gray30"
color_ninguno <- "black"
color_nsnc <- "gray60"

Es$candidatoPartido(llave_partido = "partido", llave_conocimiento = "conocimiento", respuesta_conoce = "Sí",
                     candidatos = c("era", "sasil"), corte_otro = 0.03, cliente = c("era", "sasil"),
                     colores_candidatos = rep("#5B0A1C", 6) %>% purrr::set_names(nombres_candidatos),
                     colores_partido = c("PAN" = color_pan,
                                         "PRI" = color_pri,
                                         "PRD" = color_prd,
                                         "PT" = color_pt,
                                         "Partido Verde (PVEM)" = color_pvem,
                                         "Movimiento Ciudadano (MC)" = color_mc,
                                         "MORENA" = color_morena,
                                         "Chiapas Unido" = color_chisunido,
                                         "Podemos Mover a Chiapas" = color_pmchis,
                                         "Partido Encuentro Solidario Chiapas" = color_pencsolchis,
                                         "Redes Sociales Progresistas Chiapas" = color_rspchis,
                                         "Candidato independiente" = color_otro,
                                         "Ninguno (No leer)" = color_ninguno,
                                         "Ns/Nc (No leer)" = color_nsnc,
                                         "Otro" = color_otro
                     ))

```

# Candidato saldo

```{r}
Es$candidatoSaldo(llave_opinion = "opinion", candidatos = c("era", "sasil"), positivos = c("Buena"), negativos = c("Mala"),
                   color_positivo = "orange", color_negativo = "brown")

```
# Métododología de MORENA

```{r}
candidatos <- cuestionario_demo %>%
  filter(grepl("Bloque 5", bloque)) |>
  filter(grepl("opinion_",llaves)) |>
  pull(llaves) %>%
  gsub(pattern = "opinion_", replacement = "", x = .)

atributos <- tibble(atributo = c("honesto", "mujeres", "cercano", "estado", "cumple"),
                    puntos = c(1,.5,.25,.25,.25))

Es$metodo_morena(personajes = candidatos, atributos = atributos)

```
