---
title: "Gráficas por regiones o estratos"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Gráficas por regiones o estratos}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# library(encuestar)
library(dplyr)
devtools::load_all()
```

```{r clase_regiones}
diseno <- survey::svydesign(ids = ~1, data = datos_demo |> mutate(region = sample(x = seq.int(1:6), size  = n(), replace = T)))

Gr <- Graficas$new(encuesta = encuesta_demo, tema = tema_default)

options(survey.lonely.psu = "remove")

```

# Mapa ganador

```{r, fig.width=11, fig.height=11}
Gr$Regiones$mapa_ganador(variable = "candidato_preferencia", lugar = 1)
```

# Mapa degradado numérico

```{r, fig.width=11, fig.height=11}

Gr$Regiones$mapa_degradadoNumerico(variable = "evaluacion_amlo")
```

# Heatmao conocimiento

```{r, fig.width=11, fig.height=11}
candidatos <- cuestionario_demo |>
  filter(grepl(pattern = "Bloque 3", x = bloque)) |>
  distinct(llaves) |>
  pull() |>
  gsub(pattern = "conocimiento_", replacement = "")

Gr$Regiones$heatmap_conocimiento(patron_llaveConocimiento = "conocimiento",
                                        candidatos = candidatos,
                                        respuesta = "Sí")
```

# Heatmap saldoOpinion
```{r, fig.width=11, fig.height=11}
candidatos <- cuestionario_demo |>
  filter(grepl(pattern = "Bloque 5", x = bloque)) |>
  filter(grepl(pattern = "opinion", x = llaves)) |>
  distinct(llaves) |>
  pull() |>
  gsub(pattern = "opinion_", replacement = "")

Gr$Regiones$heatmap_saldoOpinion(patron_llaveOpinion = "opinion",
                                        candidatos = candidatos,
                                        ns_nc = "Ns/Nc",
                                        cat_negativo = c("Muy mala", "Mala"),
                                        cat_regular = "Regular",
                                        cat_positivo = c("Buena", "Muy buena"))
```
